name: re3aity
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^14.7.4
  flutter_staggered_animations: ^1.1.1
  flutter_rating_bar: ^4.0.1
#  unicorndial: ^1.1.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.2.0
  google_maps_flutter: ^2.5.0
  google_maps_place_picker_mb: ^3.0.1
  image_picker: ^1.0.4
  get_storage: ^2.1.1
  pin_code_text_field: ^1.8.0
  toast: ^0.3.0
  flutter_local_notifications: ^16.1.0
  flutter_ringtone_player: ^3.2.0
  multiselect_formfield: any
  google_sign_in: ^6.1.6
  firebase_auth: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0

flutter_icons:
  image_path_android: 'assets/icons/w_logo.png'
  image_path_ios: 'assets/icons/w_logo.png'
  android: true
  ios: true
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/flare/
    - assets/images/background.jpeg

  fonts:
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
